apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: nginx1
      image: nginx
      ports:
        - containerPort: 8080
    - name: watcher
      image: afakharany/watcher
